language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
- psql -c 'create database empire_app_test;' -U postgres
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
