# Users
core_user = User.create!(username: 'Empire: core', email: 'dillonbarevalo@gmail.com', name: 'Dillon and Jack', password: 'donothackme', password_confirmation: 'donothackme')

# Weapon Classes
class1 = WeaponClass.create!(name: 'Power Weapons', description: "These weapons include such things as axes, clubs, and heavy swords. The trees for power weapons are fairly minimal and scale off of strength. These weapons are strong without any skills spent in them with average to high attack and high damage. Type 1 Weapons are wielded with either 1 or 2 hands, depending on the weapon. These weapons are somewhat lacking in defense, but to a low level character, the offensive capabilities they have are simply devastating. The problem with Class 1 weapons is they have few skills to boost their attack and few skills which add meaningful tactical choices, making them scale very poorly into the late game. No matter how high their damage gets, if you can’t hit someone, you can’t hurt them.")
class2 = WeaponClass.create!(name: "Finesse Weapons", description: "Type 2 weapons are one handed weapons that can be wielded by themselves, with another weapon (not yet), or with a shield. These weapons are often difficult to use initially but scale very well when skill points are sunk into them. They scale off of either dexterity and strength, or one of the two. Class 2 weapons have low damage and low attack numbers initially (though they usually have fairly high defensive numbers) but can scale the attack extremely well and damage numbers fairly well. What they lack in early game strength they make up for in both late game strength and the defensive capabilities (especially when coupled with a shield) to get you there.")
shields = WeaponClass.create!(name: 'shields', description: "Ultimately probably won't be a weapon class, but at the moment the website is young enough that I haven't separated them yet. It's a shield, silly.")

# Damage Types
slashing = DamageType.create!(name: 'slashing', description: 'A cut without much impact behind it. Think the cut of a light sword.')
piercing = DamageType.create!(name: 'piercing', description: 'An impact with a sharp weapon, but not one with incredible mass behind it. Think arrow or rapier thrust.')
bludgeoning = DamageType.create!(name: 'bludgeoning', description: 'A heavy impact where no sharp edge is present. Think clubs and hammers.')
bludgeoning_slashing = DamageType.create!(name: 'bludgeoning/slashing', description: 'A heavy impact with an edged weapon. Think large axes or heavy swords. Less of a slice and more of a cleave.')
bludgeoning_piercing = DamageType.create!(name: 'bludgeoning/piercing', description: 'An impact with a sharp point meant to penetrate. Think war picks and half swording.')

# Armor Types
light_armor = ArmorType.create!(name: 'Light')
medium_armor = ArmorType.create!(name: 'Medium')
heavy_armor = ArmorType.create!(name: 'Heavy')

# Conditions
off_balance = Condition.create!(name: "Off Balance", description: "A character has lost their balance and is in danger of falling over.", effect_description: "While off balance, every action that creates a MoV has a shift of -1 to the off balance character applied on it. If an character under the Off Balance condition is knocked off balance a second time that character is knocked prone. Some skills (eventually) will allow execution of maneuvers in off balance positions. Recovery may be made at the beginning of a cycle by sacrificing one’s offensive round, and movement speed is halved.")
prone = Condition.create!(name: "Prone", description: "A character has fallen over! There is not currently (and may never be) a difference between prone (on belly) and supine (on back).", effect_description: "While Prone apply a -2 shift in MoV. Recovery may be attempted at the beginning of a cycle by sacrificing half of one’s energy budget and sacrificing one’s offensive round; no movement be taken save a required Repositioning Check to stand back up (which can incur more MoV shifts upon failure).")
wounded = Condition.create!(name: "Wounded", description: 'A character has an open wound. Movement may tear it and/or cause significant pain. Bleeding is likely to follow.', effect_description: "Using more than 3/4 of round budget used inflicts 1d4 damage per excess point of energy. Heal or significant rest ends. Triggers Bleeding after one cycle. Stacking wounds increases the damage dealt (by 1d4 per energy point) but not the threshold for it. SAVE: roll under CON by 2 (two times your CON stat) to negate.")
severed_tendon = Condition.create!(name: "Severed Tendon", description: "A character has had one of their tendons cut and can no longer control the associated limb at all as they cannot engage their muscles", effect_description: "Triggered during a failed block or dodge (if triggered from Sweep count it as a leg regardless of type of defensive maneuver), where the effect is triggered for the arm that was used to block, or a leg if used for the dodge, and thus can no longer be used. If a leg has a tendon severed movement is halved and sprinting becomes impossible. Also triggers Wounded without Bleeding. If the attack that triggered severed tendon was not blocked or dodged the attacker may choose the limb to damage")
bleeding = Condition.create!(name: "Bleeding", description: "A character has begun bleeding to a significant enough extent that they must pay attention to it.", effect_description: "A bleeding character must spend 10 percent of their energy budget per round on ignoring the wound and staying in combat. Bleeding can stack exactly twice. SAVE: roll under CON by 3 (three times your CON stat) to negate.")
broken_bone = Condition.create!(name: "Broken Bone", description: "A character has broken a bone and cannot use the limb effectively anymore.", effect_description: "Cannot use limbs associated with broken bones without a massive energy drain. If limbs associated with the injury are used anyway, they incur a -1 MoV shift. SAVE: roll under CON by 1 (your CON stat) to negate.")
Condition.create!(name: "Shock", effect_description: "Shock is triggered by any specific weapon but instead by any weapon upon dealing massive damage in a single strike. If 50 percent or more of a character’s total health is dealt in one round they must make a CON by 4 check to stay stable (not enter Unconscious); if 75 percent or more, CON by 2.")

# Character Classes
warrior = CharacterClass.create!(name: "Warrior", description: "A Warrior’s primary focus is damage. They usually prefer class 1 and 3 types of weapons (explained in the weapons section), but are known to make good use out of anything they can get their hands on. Warriors use all types of armor as they vary from savage barbarians who get stronger from massive surges of adrenaline upon becoming hurt to tactical powerhouses who subtly shift their position to allow blows to glance off their heavy armor while dishing out massive damage with maximum prejudice. A Warrior’s passive skills primarily focus on improving their damage (though not so much their accuracy), their damage resistance, and modifying their energy. Their active class skills include such things as incredibly powerful strikes aimed at weapons to disarm, flurries of attacks that have a chance of denying their opponent their next offensive round, and energy manipulation such as sacrificing any defensive allocation to gain additional budget for their offensive allocation.Warriors are recommended to have high Strength and Dexterity.", motto: "The best defense is a good offense!")
soldier = CharacterClass.create!(name: 'Soldier', description: "A Soldier lives and dies by his shield. Often sporting heavy armor and using a variety of weapons (and not uncommonly being trained in more than one) the Soldier’s true strength is in his shield arm. Preferring defense to offense the Soldier strikes when his opponent is off balance, not leaving the safety of his shield unless he knows he has a solid advantage. Soldiers are almost never surprised and are nearly always prepared to defend themselves. Soldiers range from being loners who do not trust others to watch their backs to being a team based tank, making shield walls and using formations to avoid the perils of being flanked. A Soldier’s passive skills primarily focus on resistance to negative positioning conditions, improved defense, and combat readiness. Soldier active skills include such things as sacrificing offensive rounds to advance with their shield on defensive rounds in order to catch enemies off balance, taking defensive actions to protect party members instead of or in addition to themselves, and transitioning defense points that never ended up being used into attacks in the following round.", motto: "Perhaps the pen is mightier than the sword, perhaps it isn’t. I do not know. What I can tell you, however, is that the shield is mightier than the sword.")

# Weapon Types
sword = WeaponType.create!(name: "Sword")
light_shield = WeaponType.create!(name: 'Light shield')
heavy_shield = WeaponType.create!(name: 'Heavy shield')
axe = WeaponType.create!(name: 'Axe')
club = WeaponType.create!(name: 'Club')
pick = WeaponType.create!(name: 'War pick')

# Weapons
battle_axe = Weapon.create!(user_id: core_user.id, weapon_type_id: axe.id, name: 'Battle Axe', description: 'A large, 2 handed axe with heavy cutting power and good reach. A Dane Axe is a good example.', defense_die_number: 1, defense_die_size: 10, flat_defense_bonus: 5, defense_energy_modifier: 1, extra_block_cost: 30, extra_attack_cost: 30, hands_used: 2)
war_pick = Weapon.create!(user_id: core_user.id, weapon_type_id: pick.id, name: 'War Pick', description: 'A large, 2 handed haft with a spike protruding from one side at the end. Many war hammers feature such a pick.', defense_die_number: 1, defense_die_size: 10, flat_defense_bonus: 5, defense_energy_modifier: 1, extra_block_cost: 30, extra_attack_cost: 35, hands_used: 2)
falchion = Weapon.create!(user_id: core_user.id, weapon_type_id: sword.id, name: 'falchion', description: 'A medium length, slightly curved, broad bladed, heavy sword meant for brutal chops that can cleave through armor and sever limbs.', defense_die_number: 1, defense_die_size: 4, flat_defense_bonus: 5, defense_energy_modifier: 1, extra_block_cost: 30, extra_attack_cost: 27, hands_used: 1)
hand_axe = Weapon.create!(user_id: core_user.id, weapon_type_id: axe.id, name: 'Hand Axe', description: "A small, one handed axe that can strike with precision and efficiency. Its head heavy nature make its chops surprisingly powerful.", defense_die_number: 1, defense_die_size: 6, flat_defense_bonus: 5, defense_energy_modifier: 0.5, extra_block_cost: 25, extra_attack_cost: 25, hands_used: 1)
mace = Weapon.create!(user_id: core_user.id, weapon_type_id: club.id, name: 'Mace', description: 'A metal weight on the end of a handle maces come in many shapes and sizes. They all specialize in dealing massive impact damage with a head heavy, powerful strike.', defense_die_number: 1, defense_die_size: 4, flat_defense_bonus: 5, defense_energy_modifier: 1, extra_block_cost: 35, extra_attack_cost: 30, hands_used: 1)
side_sword = Weapon.create!(user_id: core_user.id, weapon_type_id: sword.id, name: 'Side Sword', description: 'A well balanced, straight, tapering sword. Fairly thin and mobile it can both cut and stab fairly well but does not excel in any specific category.', defense_die_number: 1, defense_die_size: 6, flat_defense_bonus: 8, defense_energy_modifier: 1.5, extra_block_cost: 25, extra_attack_cost: 25, hands_used: 1)
